services:

  jaeger:
    image: ${JAEGERTRACING_IMAGE}
    networks:
      - todonet
    command:
      - "--memory.max-traces=5000"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    #      - "--query.base-path=/jaeger/ui"
    ports:
      - "16686:16686"
    restart: unless-stopped
    environment:
      - METRICS_STORAGE_TYPE=prometheus

  otelcol:
    image: ${COLLECTOR_CONTRIB_IMAGE}
    restart: unless-stopped
    networks:
      - todonet
    command: ["--config=/etc/otel-collector-config.yml", ""]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"
    depends_on:
      - jaeger

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    networks:
      - todonet
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_SERVICE_PORT}:${PROMETHEUS_SERVICE_PORT}"

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - node.name=es
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es,es2
      - discovery.seed_hosts=es2
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - todonet

  es2:
    container_name: es2
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - node.name=es2
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es,es2
      - discovery.seed_hosts=es
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9201:9200"
    networks:
      - todonet

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.authc.http.enabled=false
      - xpack.security.authc.http.autoSchemesEnabled=false
      - xpack.security.authc.selector.enabled=false
      - elasticsearc.ssl.verificationMode=none
      - elasticsearc.ssl.alwaysPresentCertificate=false
      - elasticsearch.hosts=['http://es:9200']
    networks:
      - todonet
    depends_on:
      - es

networks:
  todonet: